import { printElementDocument } from "../lib/listDocuments";
import { Printer } from "lucide-react";
import Modal from "./Modal";
import { money } from "../lib/catalog";

function dateTime(value) {
  if (!value) return "—";

  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

const rows = [
  ["Opening cash", "opening", 1],
  ["Cash sales", "cash_sales", 1],
  ["Cash refunds", "cash_refunds", -1],
  ["Other cash in", "cash_income", 1],
  ["Cash expenses", "cash_expenses", -1],
  ["Supplier payments", "supplier_payments", -1]
];

function CurrencyReport({ currency, totals, closed }) {
  const values = totals?.[currency] || {};

  return (
    <section className="register-report-currency">
      <h3>{currency} drawer</h3>

      <div className="register-report-lines">
        {rows.map(([label, field, sign]) => (
          <div key={field}>
            <span>{label}</span>
            <strong>
              {sign < 0 ? "−" : ""}
              {money(Math.abs(Number(values[field] || 0)), currency)}
            </strong>
          </div>
        ))}

        <div className="register-report-total">
          <span>Expected cash</span>
          <strong>{money(values.expected || 0, currency)}</strong>
        </div>

        {closed && (
          <>
            <div>
              <span>Counted cash</span>
              <strong>{money(values.counted || 0, currency)}</strong>
            </div>
            <div className="register-report-variance">
              <span>Variance</span>
              <strong>{money(values.variance || 0, currency)}</strong>
            </div>
          </>
        )}
      </div>
    </section>
  );
}

export default function CashRegisterReportModal({
  report,
  shop,
  onClose
}) {
  if (!report) return null;

  const session = report.session;
  const closed = session.status === "closed";

  return (
    <Modal
      title={closed ? "Cash register closing report" : "Cash register report"}
      onClose={onClose}
      wide
    >
      <div className="register-report-wrapper">
        <article className="register-report-document">
          <header>
            {shop?.shop_logo_url && (
              <img src={shop.shop_logo_url} alt="" />
            )}
            <h2>{shop?.shop_name || "Tiny POS"}</h2>
            <strong>
              {closed
                ? "CASH REGISTER CLOSING REPORT"
                : "OPEN CASH REGISTER REPORT"}
            </strong>
          </header>

          <div className="register-report-meta">
            <div>
              <span>Session</span>
              <strong>{session.session_number}</strong>
            </div>
            <div>
              <span>Register</span>
              <strong>{session.register_name}</strong>
            </div>
            <div>
              <span>Opened</span>
              <strong>{dateTime(session.opened_at)}</strong>
            </div>
            <div>
              <span>Closed</span>
              <strong>{dateTime(session.closed_at)}</strong>
            </div>
            <div>
              <span>Status</span>
              <strong>{session.status.toUpperCase()}</strong>
            </div>
          </div>

          <div className="register-report-grid">
            <CurrencyReport
              currency="USD"
              totals={report.totals}
              closed={closed}
            />
            <CurrencyReport
              currency="KHR"
              totals={report.totals}
              closed={closed}
            />
          </div>

          {(session.opening_note || session.closing_note) && (
            <div className="register-report-notes">
              {session.opening_note && (
                <div>
                  <strong>Opening note</strong>
                  <p>{session.opening_note}</p>
                </div>
              )}
              {session.closing_note && (
                <div>
                  <strong>Closing note</strong>
                  <p>{session.closing_note}</p>
                </div>
              )}
            </div>
          )}

          <footer>
            Generated by Tiny POS
          </footer>
        </article>

        <div className="receipt-actions">
          <button
            type="button"
            className="secondary-button"
            onClick={onClose}
          >
            Close
          </button>
          <button
            type="button"
            className="primary-button"
            onClick={() => printElementDocument({ title: "Cash Register Report", selector: ".register-report-document", page: "A4 landscape" })}
          >
            <Printer size={18} />
            Print report
          </button>
        </div>
      </div>
    </Modal>
  );
}
