import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {getSupabase} from '../lib/supabase';
const C=createContext(null);
function apply(p){const r=document.documentElement,t=p?.theme||'system',a=p?.accent_color||'#2563eb';r.dataset.theme=t;r.dataset.forceTheme=t==='system'?'':t;r.style.setProperty('--accent',a)}
export function AuthProvider({children}){const [supabase,setSupabase]=useState();const [session,setSession]=useState();const [profile,setProfile]=useState();const [preferences,setPreferences]=useState();const [shop,setShop]=useState();const [loading,setLoading]=useState(true);const [error,setError]=useState('');
async function load(client,s){if(!s){setProfile();setPreferences();setShop();return}const id=s.user.id;const {data:p,error:e1}=await client.from('profiles').select('*,organizations(*),branches(*)').eq('id',id).single();if(e1)throw e1;const {data:u,error:e2}=await client.from('user_preferences').select('*').eq('user_id',id).single();if(e2)throw e2;const {data:a,error:e3}=await client.from('app_settings').select('*').eq('organization_id',p.organization_id).single();if(e3)throw e3;setProfile(p);setPreferences(u);setShop(a);apply(u)}
useEffect(()=>{let sub,m=true;(async()=>{try{const c=await getSupabase();if(!m)return;setSupabase(c);const {data}=await c.auth.getSession();setSession(data.session);await load(c,data.session);const x=c.auth.onAuthStateChange(async(_,s)=>{setSession(s);try{await load(c,s)}catch(e){setError(e.message)}});sub=x.data.subscription}catch(e){setError(e.message)}finally{if(m)setLoading(false)}})();return()=>{m=false;sub?.unsubscribe()}},[]);
async function signIn(email,password){const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setSession(data.session);await load(supabase,data.session)}
async function signOut(){const {error}=await supabase.auth.signOut();if(error)throw error}
async function savePreferences(v){const {data,error}=await supabase.from('user_preferences').update(v).eq('user_id',session.user.id).select().single();if(error)throw error;setPreferences(data);apply(data)}
const value=useMemo(()=>({supabase,session,profile,preferences,shop,loading,error,signIn,signOut,savePreferences}),[supabase,session,profile,preferences,shop,loading,error]);return <C.Provider value={value}>{children}</C.Provider>}
export const useAuth=()=>useContext(C);
